### ISSUE TITLE
Influx Error

### ISSUE THREAD

**Issue by opvizordz** [regel/loudml#10]
I followed the guide here using Influxdb 1.5 and loudml 1.2.1: https://medium.com/swlh/easy-machine-learning-tricks-for-linux-developers-in-2018-f697d153d904

I created the model based on:

```
---
name: my-timeseries-model
type: timeseries
default_datasource: influx
# Size of buckets for data aggregation and prediction
bucket_interval: 5m
# Number of preceding buckets required to predict the next bucket
span: 3
interval: 60s
offset: 30
max_evals: 5
features:
- name: avg_cpu_load
  measurement: system
  metric: avg
  field: cpu_load
  default: 0

```
config file:
root@deb9:/etc/loudml# cat config.yml
```
---
datasources:
 - name: influx
   type: influxdb
   addr: localhost
   database: telegraf

storage.path: /var/lib/loudml

server.listen: localhost:8077
```
loudml create-model /home/test/model.yml

Creating the model works fine, but the train command fails:
_loudml train my-timeseries-model --from now-1d --to now_
```
/usr/lib/python3/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
ERROR:root:influxdb
```
**ERROR:root:influxdb**

This error shows no matter if influxdb is running on localhost or on another server. I also tried to set the 
addr: localhost to addr: http://127.0.0.1:8086

Any idea? Or log file I can configure (debug option)?

Thanks, Dennis
