### ISSUE TITLE
Verify GPU Usage

### ISSUE THREAD

**Issue by lephisto** [regel/loudml#104]
Hi Sebastien,

is there any way to verify that loudml and the underlying tensorflow is acutally using the GPU?

I have set this:

```
inference:
  num_cpus: 1
  num_gpus: 1

training:
  num_cpus: 1
  num_gpus: 1
```
.. but I can't be sure, that tensorflow actually did initialize cuda cores.

thanks in advance..
