### ISSUE TITLE
Pulling latest-devel in Docker compose results in "Unable to Find Datasource" (Datasource vs. Bucket?)

### ISSUE THREAD

**Issue by hatdropper1977** [regel/loudml#151]
I cloned and ran the docker-compose file located [here](https://github.com/regel/loudml/tree/master/docker/compose).

It pulled the following images...

| Container         | Version      | Image ID     |
|-------------------|--------------|--------------|
| influxdb          | 1.7.8        | c0c0eb7f0bc1 |
| loudml/loudml     | latest-devel | b80613b0c560 |
| loudml/chronograf | 1.6.1        | 0d4d1430c386 | 

When I go to LoudML-Chronograf, I get an **Unable to Find Datasource** error.

![Screen1](https://user-images.githubusercontent.com/3123188/66429713-a0bcfa00-e9e6-11e9-94f6-afdd1040e61d.png)

![Screen2](https://user-images.githubusercontent.com/3123188/66429721-a4e91780-e9e6-11e9-8921-b491e26d25ac.png)

The LoudML logs record that the LoudML API does not contain a **datasources** endpoint (Returns **404** - not found).

```bash
$ docker logs -f loudml_loudml_1
INFO:root:starting Loud ML server on 0.0.0.0:8077
INFO:schedule:Running job Every 1 minute do daemon_clear_jobs() (last run: [never], next run: 2019-10-08 18:49:06)
INFO:schedule:Running job Every 1 minute do daemon_clear_jobs() (last run: 2019-10-08 18:49:06, next run: 2019-10-08 18:50:06)
172.23.0.6 - - [2019-10-08 18:50:12] "GET /datasources HTTP/1.1" 404 139 0.000859
172.23.0.6 - - [2019-10-08 18:50:12] "GET /datasources HTTP/1.1" 404 139 0.000481
172.23.0.6 - - [2019-10-08 18:50:27] "GET /datasources HTTP/1.1" 404 139 0.000705
172.23.0.6 - - [2019-10-08 18:50:27] "GET /datasources HTTP/1.1" 404 139 0.000638
INFO:schedule:Running job Every 1 minute do daemon_clear_jobs() (last run: 2019-10-08 18:50:06, next run: 2019-10-08 18:51:06)
172.23.0.6 - - [2019-10-08 18:51:56] "GET /models HTTP/1.1" 200 110 0.001031
172.23.0.6 - - [2019-10-08 18:51:58] "GET / HTTP/1.1" 200 231 0.001631
172.23.0.6 - - [2019-10-08 18:51:58] "GET /datasources HTTP/1.1" 404 139 0.000484
INFO:schedule:Running job Every 1 minute do daemon_clear_jobs() (last run: 2019-10-08 18:51:06, next run: 2019-10-08 18:52:06)
```
If I CURL the **datasources** API, I receive an **unknown endpoint** error.

```bash
$ curl -XGET 0.0.0.0:8077/datasources
unknown endpoint
```

If I CURL the **buckets** API, I receive a response.

```bash
$ curl -XGET 0.0.0.0:8077/buckets | jq
[
  {
    "addr": "influxdb:8086",
    "database": "telegraf",
    "measurement": "loudml",
    "name": "influx",
    "type": "influxdb"
  },
  {
    "addr": "kapacitor:9092",
    "database": "from_loudml",
    "measurement": "loudml",
    "name": "kapacitor",
    "type": "influxdb"
  }
]
```

I believe by pulling **loudml/loudml:devel-latest** I pull the **master** version which replaces the **datasources** API with **buckets** API.

Is this what causes the **unknown endpoint** error in the Chronograf UI?

**Comment by hatdropper1977** [comment]
Update:  I do see an issue w/ pulling **latest-devel.**

I changed [docker-compose](docker-compose) to the following:
```yaml
services:
  loudml:
    image: loudml/community:1.5.0
    volumes:
      - ./etc/loudml.yml:/etc/loudml/config.yml:ro
      - ./var/loudml:/var/lib/loudml
    ports:
      - "8077:8077"
    depends_on:
      - influxdb

<snip>
```

I then changed [etc/loudml.yml](https://github.com/regel/loudml/blob/master/docker/compose/etc/loudml.yml) to the following:

```yaml
---
datasources:
  - name: influx
    type: influxdb
    addr: influxdb:8086
    database: telegraf
    measurement: loudml
  - name: kapacitor
    type: influxdb
    addr: kapacitor:9092
    database: from_loudml
    measurement: loudml

storage:
  path: /var/lib/loudml

server:
  listen: 0.0.0.0:8077
```

When I brought the container up, **LoudML-Chronograf** can now connect to the data source.

![Screen3](https://user-images.githubusercontent.com/3123188/66432721-b9c8a980-e9ec-11e9-920c-f8f76bd4157f.png)

**Comment by regel** [comment]
Thanks. OK. The API in 1.6 has breaking changes (eg returning arrays rather than single elements).

The JavaScript code needs a refresh. We will be able to add all buckets dynamically at run time and therefore avoid the « datasource not found » exception.

**Comment by simeonwislang** [comment]
Experiencing the same issue as above with latest-devel. Reverting back to 1.5 works. Thanks @hatdropper1977 !

**Comment by KevinM23** [comment]
Hi @hatdropper1977 could you please provide the full docker-compose.yml file? I do not know what exactly I'm missing, but I experience the same problem as you and changing the loudml to the 1.5.0 does not solve the problem:

docker-compose.yml:
```
# This is a Docker Compose file to work with Loud ML and an InfluxDB stack.

version: "3"

services:
  loudml:
    image: loudml/community:1.5.0
    volumes:
      - ./etc/loudml.yml:/etc/loudml/config.yml:ro
      - ./var/loudml:/var/lib/loudml
    ports:
      - "8077:8077"
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./var/influxdb:/var/lib/influxdb

  chronograf:
    image: loudml/chronograf:latest
    depends_on:
      - influxdb
      - loudml
      - kapacitor
    ports:
      - "8888:8888"
    volumes:
      - ./var/chronograf:/var/lib/chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      LOUDML_URL: http://loudml:8077
      KAPACITOR_URL: http://kapacitor:9092

  kapacitor:
    image: kapacitor:latest
    depends_on:
      - influxdb
    volumes:
      - ./var/kapacitor:/var/lib/kapacitor
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086

  telegraf:
    image: telegraf:latest
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    environment:
      INFLUXDB_URL: http://influxdb:8086
```

And my loudml.yml:
```datasources:
  - name: influx
    type: influxdb
    addr: influxdb:8086
    database: telegraf
    measurement: loudml
  - name: kapacitor
    type: influxdb
    addr: kapacitor:9092
    database: from_loudml
    measurement: loudml

storage:
  path: /var/lib/loudml

server:
  listen: 0.0.0.0:8077
```

What I noticed is that my ~/etc/telegraf.conf (which is in the same folder as the loudml.yml) is empty. 

Hope someone can help with this.

Thanks!

**Comment by KevinM23** [comment]
Also,  while using the code mentioned above I see that the chronograf version is 1.6.1

**Comment by hatdropper1977** [comment]
@KevinM23 it appears your loudml.yml is missing the **datasources** stanza header.

Mine looks like:

```yaml
---
datasources:
  - name: influx
    type: influxdb
    addr: influxdb:8086
    database: telegraf
    measurement: loudml
  - name: kapacitor
    type: influxdb
    addr: kapacitor:9092
    database: from_loudml
    measurement: loudml

storage:
  path: /var/lib/loudml

server:
  listen: 0.0.0.0:8077
```

I pasted my **docker-compose** file, with the versions that worked for me below:

```yaml
version: "2"

services:
  loudml:
    image: loudml/community:1.5.0
    volumes:
      - ./etc/loudml.yml:/etc/loudml/config.yml:ro
      - ./var/loudml:/var/lib/loudml
    ports:
      - "8077:8077"
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.7.8
    ports:
      - "8086:8086"
    volumes:
      - ./var/influxdb:/var/lib/influxdb

  chronograf:
    image: loudml/chronograf:1.6.1
    depends_on:
      - influxdb
      - loudml
      - kapacitor
    ports:
      - "8888:8888"
    volumes:
      - ./var/chronograf:/var/lib/chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      LOUDML_URL: http://loudml:8077
      KAPACITOR_URL: http://kapacitor:9092

  kapacitor:
    image: kapacitor:1.5.3
    depends_on:
      - influxdb
    volumes:
      - ./var/kapacitor:/var/lib/kapacitor
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086

  telegraf:
    image: telegraf:1.12
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    environment:
      INFLUXDB_URL: http://influxdb:8086
```
