### ISSUE TITLE
loudml/chronograf with nginx

### ISSUE THREAD

**Issue by sve71** [regel/loudml#172]
Hello there,
I’m using TICK-L stack that was installed via docker. I’ve extended the existing bundle with one more container with nginx inside. The thing is loudml/chronograf doesn’t work properly in the configuration. When I try to refer to the Web-interface of Chronograf by using the link http://host:8888/chronograf, no pages are displayed.
I’ve tried [the](https://github.com/influxdata/chronograf/issues/845) recommendations. Such menus as Dashboards, Data Explorer, etc. work fine, except the LoudML extension. The error occurs:
`cannot get models`:
It’s possible the issue happens due to adding BASE_PATH: /chronograf environment variable along with INFLUXDB_URL: http://influxdb:8086 and LOUDML_URL: http://loudml:8077.

Any ideas how to decide it?

**Comment by regel** [comment]
This could be the base path. I never used this environment variable before.

Any logs in the Docker console?

The chronograf server is written in Go and encapsulates the React App in addition to reverse proxy.

Can you share a snippet of the new docker compose file with Nginx?

**Comment by sve71** [comment]
Hello,

As I understand according the documentation the BASE_PATH is the URL path prefix under which all chronograf routes will be mounted.

I’m using Ansible to deploy the current setup. The snippet you’ve mentioned (with discussed env variable):
```
- name: Install/Uninstall 'loudml/chronograf' container
  docker_container:
    name: chronograf
    image: "loudml/chronograf"
    ports:
      - 8888:8888/tcp
    volumes:
      - "../../roles/chronograf/var/chronograf:/var/lib/chronograf"
    networks:
      - name: capture
        aliases:
          - chronograf
    env:
      BASE_PATH: "/chronograf"
      INFLUXDB_URL: "http://influxdb:8086"
      LOUDML_URL: "http://loudml:8077"
    restart: yes
    state: "{{state}}"
```
 The _docker logs chronograf_ command shows just the following:
```
time="2020-01-05T16:39:33Z" level=info msg="Serving chronograf at http://[::]:8888" component=server
time="2020-01-05T16:39:33Z" level=info msg="Reporting usage stats" component=usage freq=24h reporting_addr="https://usage.influxdata.com" stats="os,arch,version,cluster_id,uptime"
```

What other logs (dumps of network traffic, chronograf's logs inside its container maybe) will be useful for the analysis?

**Comment by gilangcp** [comment]
Hi @sve71 , I believe I got similar issue, However I also have a workaround. The thing is that the       LOUDML_URL not working if you have custom base path. For example, I use `https://myurl.com/loudml/chronograf `as the base url, The Chronograf always look at this URL: `https://myurl.com/loudml/chronograf/loudml/api/buckets ` not the `LOUDML_URL` when I click the LoudML tab.

The work around is that you need to add a new location directive in nginx  to LoudML. for example, I add this to my nginx.conf

```
        location ^~ /loudml/chronograf/loudml/api/ {
                rewrite /loudml/chronograf/loudml/api/(.*) /$1 break; #Only pass LoudML path eg: /buckets
                proxy_ignore_client_abort on;
                proxy_pass http://localhost:8077; #LoudML location
                proxy_set_header Host $host;
        }

```

**Comment by sve71** [comment]
Hi, @gilangcp
Thx a lot for your feedback.

The location directive
`location ^~ /loudml/chronograf/loudml/api/`
This is exactly what I needed. With the configuration you wrote above everything works well.

Let’s make a conclusion for other participants for the future.
If it’s needed to deploy LoudML installation with using proxy server, such as nginx, we may to do the next steps:
- define how our URL has to look like. For example,
`http://192.168.0.100/cronograf`
- configure the BASE_PATH environment variable in the docker-compose.yml file. For example,
```
environment:
  BASE_PATH: “/chronograf”
  INFLUXDB_URL: http://influxdb:8086
  LOUDML_URL: http://loudml:8077
  KAPACITOR_URL: http://kapacitor:9092
```
- in a proxy (nginx) configuration file it’s needed to add the following location
```
location /chronograf {
  proxy_set_header   Host $host;
  proxy_pass http://chronograf:8888;
}

location ^~ /chronograf/loudml/api/ {
  rewrite /chronograf/loudml/api/(.*) /$1 break;
  proxy_ignore_client_abort on;
  proxy_set_header Host $host;
  proxy_pass http://loudml:8077;
}
```

BR, Sergey.
