### ISSUE TITLE
configured scheduled jobs not synced with model create/delete

### ISSUE THREAD

**Issue by toni-moreno** [regel/loudml#401]
Hi @regel , I've configured some scheduled jobs from my loudml-config.yml

```
scheduled_jobs:
  - name: "forecast({{model_name}}) every five minutes"
    relative_url: "/models/{{model_name}}/_forecast"
    method: post
    params:
      from: "now-1h"
      to: "now+1h"
      save_output_data: True
      output_bucket: "test-loudml"
    every:
      count: 5
      unit: minutes
  - name: "train({{model_name}}) every day at 1am"
    relative_url: "/models/{{model_name}}/_train"
    method: post
    params:
      from: "now-1d"
      to: "now"
      continue: True
    every:
      count: 1
      unit: day
      at: "01:00"
  - name: "train({{model_name}}) every sunday at 2am"
    relative_url: "/models/{{model_name}}/_train"
    method: post
    params:
      from: "now-7d"
      to: "now"
    every:
      count: 1
      unit: sunday
      at: "02:00"
  - name: "train({{model_name}}) every 28 days at 3am"
    relative_url: "/models/{{model_name}}/_train"
    method: post
    params:
      from: "now-28d"
      to: "now"
    every:
      count: 28
      unit: days
      at: "03:00"
```

I've created model  'model_A', but scheduled jobs only has appeared on loudml restart service. 
In the same way when deleting model, scheduled jobs still exists, until removed by hand or service restart.
 
```
> list-models
model_A
> delete-model model_A
> list-models
> list-scheduled-jobs
forecast(model_A) every five minutes
train(model_A) every 28 days at 3am
train(model_A) every day at 1am
train(model_A) every sunday at 2am
```

Could be nice if configured scheduled jobs and model life cycle could be synced .
Thank you very much!
