### ISSUE TITLE
Forecasting either out of bound or no data found

### ISSUE THREAD

**Issue by MatosAndre** [regel/loudml#414]
Hi, I am using this configuration:
config.yml:

```
buckets:
  - name: my-influx-datasource
    type: influxdb
    addr: localhost:8086
    database: databroadcaster
    retention_policy: autogen
    measurement: loudml
    annotation_db: loudml
    create_database: false

storage:
 path: /var/lib/loudml

server:
  listen: localhost:8077
```
And my test.yml is:

```
 name: test-model
 type: donut
 default_bucket: my-influx-datasource
 forecast: 6
 bucket_interval: 0.01s
 span: 12

 interval: 0.01s
 offset: 0.005s
 max_evals: 20

 features:
 - name: avg_test
   measurement: "av_Master.ActualPosition"
   field: value
   metric: avg
   default: 0

```
I am using Loud ML shell 1.6.3

I managed to train my model with no errors however when I try to forecast:
`forecast-model test-model --from now-1d --to now+1d`
I receive the message: `no data found for time range 2020-08-27T11:20:55.130Z-2020-08-29T11:20:55.250Z`

And even if I try to evaluate my model with the same time range that I used to train:
`eval-model test-model --from 2020-08-24T13:21:15.853624408Z --to 2020-08-24T13:21:25.843642001Z`
I receive the message:
`index 1010 is out of bounds for axis 0 with size 1010`

Any idea what can be the problem of both aspects?
