### ISSUE TITLE
LoudML not detecting datasources

### ISSUE THREAD

**Issue by Milan-Faizal** [regel/loudml#65]
Hai, I'm running the TICK-L stack using docker-compose and everything is running without any errors. However loudML add-on is showing that "Unable to find loudML datasource for selected database. Check configuration".
![screenshot from 2018-10-27 16-24-37](https://user-images.githubusercontent.com/22698793/47604382-b411c800-da16-11e8-82ef-d4076279e813.png)

![screenshot from 2018-10-27 16-24-56](https://user-images.githubusercontent.com/22698793/47604384-c429a780-da16-11e8-8e1b-4a4f49dbea13.png)
I get a response on "localhost:8077" as 

```

host_id | "e2ed2e41c268b2c8c464554ad53ebb3e"
tagline | "The Disruptive Machine Learning API"
version | "1.4"

```
But when i try "localhost:8077/datasources" ,I'm not getting any response.

My **config.yml** file is given below:

```
---
datasources:
  - name: influx
    type: influxdb
    addr: influxdb:8086
    database: telegraf
  - name: kapacitor
    type: influxdb
    addr: kapacitor:9092
    database: from_loudml

storage:
  path: /var/lib/loudml

server:
listen: 0.0.0.0:8077

```

And **docker-compose.yml** is:
```

# This is a Docker Compose file to work with Loud ML and an InfluxDB stack.

version: "2"

services:
  loudml:
    image: loudml/community
    volumes:
      - ./etc/loudml/config.yml:/etc/loudml/loudml.yml:ro
      - ./var/loudml:/var/lib/loudml
    ports:
      - "8077:8077"
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./var/influxdb:/var/lib/influxdb

  chronograf:
    image: loudml/chronograf
    depends_on:
      - influxdb
      - loudml
      - kapacitor
    ports:
      - "8888:8888"
    volumes:
      - ./var/chronograf:/var/lib/chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      LOUDML_URL: http://loudml:8077
      KAPAITOR_URL: http://kapacitor:9092

  kapacitor:
    image: kapacitor:latest
    depends_on:
      - influxdb
    volumes:
      - ./var/kapacitor:/var/lib/kapacitor
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086

  telegraf:
    image: telegraf:latest
    volumes:
      - ./etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    environment:
      INFLUXDB_URL: http://influxdb:8086
```

Why is it not showing any datasources?
