### ISSUE TITLE
Predictions are not saved to the output bucket

### ISSUE THREAD

**Issue by dgdevops** [regel/loudml#685]
Hello Everyone,

Recently I have been experimenting with LoudML & Chronograf to take advantage of the Machine Learning capabilities.
I read in the official documentation that there is a way to use a bucket as an output for the predictions so I created & mounted the following LoudML configuration:

```
buckets:
  - name: telegraf
    type: influxdb
    addr: [redacted]:8086
    database: metrics
   - name: output
    type: influxdb
    addr: [redacted]:8086
    database: loudml
    create_database: true
server:
  listen: 0.0.0.0:8077
```
After the LoudML pod (using loudml/loudml:latest image) comes up I start the Chronograf pod (using loudml/chronograf:latest image) as well with the `INFLUXDB_URL` & `LOUDML_URL` specified. Once Chronograf is up I specify the query in the Data Explorer and I create a ML task for it using the "Create baseline" button. The task gets created successfully and the training also finishes flawlessly. The next step would be to "Run" the predictions and view them live, after clicking the "Run" button the predictions are showing "Running" status but when I open the dashboard I can see no data. Based on the dashboard panel's configuration the data is supposed to be read from the loudml database however it is not even created.

When I check the LoudML pod's logs I can see the following POST request: `POST /models/demo/_start?output_bucket=loudml&save_output_data=true&flag_abnormal_data=true HTTP/1.1"`
Based on that the loudml output_bucket is chosen as output, however I don't have a bucket with that name configured so I renamed the "output" bucket to "loudml" to match the name in the POST request and started the process all over again however the loudml database is neither created nor contains any data. In the hope to have this fixed I created the loudml database but the data predictions are not saved to that database and the dashboard is till showing no data.

Could someone please guide me on how the predictions can be saved either to a new database (such as loudml) or in the source database but with _predictions annotations?
